# Generated by Django 2.2.7 on 2019-11-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.CharField(max_length=16)),
                ('employee_date', models.DateField()),
                ('terminated_date', models.DateField(blank=True, default=None, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Person')),
            ],
        ),
    ]
